### ISSUE TITLE
API not responding

### ISSUE THREAD

**Issue by mohsr** [dyang108/diningdata#2]
Hi,
The REST API response for generic menus doesn't seem to return any dining hall data anymore. The menu-id and credits fields are filled, but the data itself is empty.
Here is an example request and response:
Request: `GET https://tuftsdiningdata.herokuapp.com/menus/carm/29/1/2019`
Response: `{"menu-id": "carm-29-1-2019", "data": {}, "credit": "https://github.com/dyang108/diningdata"}`

**Comment by dyang108** [comment]
hi @mohsr thanks for letting me know. unfortunately it looks like the Tufts dining site is throwing a 500: http://menus.tufts.edu/foodpro/location.asp

since the api scrapes from the tufts site, i don't think this'll get fixed until their site is back up...

hopefully they won't change the structure...

**Comment by mohsr** [comment]
Seems to be back up. Thanks!
